// Code generated by hertz generator.

package social

import (
	"context"

	social "github.com/Sna-ken/videoweb/biz/model/social"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /follow/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FollowActionResp)

	c.JSON(consts.StatusOK, resp)
}

// FollowList .
// @router /follow/list [GET]
func FollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FollowListResp)

	c.JSON(consts.StatusOK, resp)
}

// FollowerList .
// @router /follower/list [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FollowerListResp)

	c.JSON(consts.StatusOK, resp)
}

// FriendList .
// @router /friend/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FriendListResp)

	c.JSON(consts.StatusOK, resp)
}
