// Code generated by hertz generator.

package social

import (
	"context"
	"errors"

	social "github.com/Sna-ken/videoweb/biz/model/social"
	service "github.com/Sna-ken/videoweb/biz/service/social"
	"github.com/Sna-ken/videoweb/pkg/e"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FollowAction .
// @router /follow/action [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	socialService := service.NewSocialService(ctx)
	userID := c.GetString("user_id")

	err = socialService.FollowActionService(&req, userID)
	if err != nil {
		switch {
		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &social.FollowActionResp{
				Base: &social.Base{Code: consts.StatusInternalServerError, Msg: "follow failed:" + err.Error()},
			})
			return
		case errors.Is(err, e.ErrUserNotFound):
			c.JSON(consts.StatusUnauthorized, &social.FollowActionResp{
				Base: &social.Base{Code: consts.StatusUnauthorized, Msg: "follow failed:" + err.Error()},
			})
			return
		case errors.Is(err, e.ErrIDAndNameInconsistent):
			c.JSON(consts.StatusBadRequest, &social.FollowActionResp{
				Base: &social.Base{Code: consts.StatusBadRequest, Msg: "follow failed:" + err.Error()},
			})
			return
		case errors.Is(err, e.ErrOprationRepeated):
			c.JSON(consts.StatusBadRequest, &social.FollowActionResp{
				Base: &social.Base{Code: consts.StatusBadRequest, Msg: "follow failed:" + err.Error()},
			})
			return
		case errors.Is(err, e.ErrCanNotSelfFollow):
			c.JSON(consts.StatusBadRequest, &social.FollowActionResp{
				Base: &social.Base{Code: consts.StatusBadRequest, Msg: "follow failed:" + err.Error()},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, social.FollowActionResp{
		Base: &social.Base{Code: consts.StatusOK, Msg: "follow seccussfully"},
	})
}

// FollowList .
// @router /follow/list [GET]
func FollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowListReq
	resp := new(social.FollowListResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	socialService := service.NewSocialService(ctx)
	userID := c.GetString("user_id")

	err, resp = socialService.FollowListService(&req, userID)
	if err != nil {
		switch {
		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &social.FollowListResp{
				Base: &social.Base{Code: consts.StatusInternalServerError, Msg: "follow list fetched failed:" + err.Error()},
			})
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

// FollowerList .
// @router /follower/list [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowerListReq
	resp := new(social.FollowerListResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	socialService := service.NewSocialService(ctx)
	userID := c.GetString("user_id")

	err, resp = socialService.FollowerListService(&req, userID)
	if err != nil {
		switch {
		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &social.FollowerListResp{
				Base: &social.Base{Code: consts.StatusInternalServerError, Msg: "follower list fetched failed:" + err.Error()},
			})
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

// FriendList .
// @router /friend/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListReq
	resp := new(social.FriendListResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	socialService := service.NewSocialService(ctx)
	userID := c.GetString("user_id")

	err, resp = socialService.FriendListService(&req, userID)
	if err != nil {
		switch {
		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &social.FriendListResp{
				Base: &social.Base{Code: consts.StatusInternalServerError, Msg: "follower list fetched failed:" + err.Error()},
			})
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}
