// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"github.com/Sna-ken/videoweb/kitex_gen/model"
)

type RegisterReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

type RegisterResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_Base_DEFAULT *model.BaseResp

func (p *RegisterResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RegisterResp_Base_DEFAULT
	}
	return p.Base
}
func (p *RegisterResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *RegisterResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

type LoginReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	MfaCode  string `thrift:"mfa_code,3" frugal:"3,default,string" json:"mfa_code"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}

func (p *LoginReq) GetMfaCode() (v string) {
	return p.MfaCode
}
func (p *LoginReq) SetUsername(val string) {
	p.Username = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}
func (p *LoginReq) SetMfaCode(val string) {
	p.MfaCode = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

type LoginResp struct {
	Base          *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Authorization string          `thrift:"authorization,2" frugal:"2,default,string" json:"authorization"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_Base_DEFAULT *model.BaseResp

func (p *LoginResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LoginResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginResp) GetAuthorization() (v string) {
	return p.Authorization
}
func (p *LoginResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *LoginResp) SetAuthorization(val string) {
	p.Authorization = val
}

func (p *LoginResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

type GetMFAqrReq struct {
}

func NewGetMFAqrReq() *GetMFAqrReq {
	return &GetMFAqrReq{}
}

func (p *GetMFAqrReq) InitDefault() {
}

func (p *GetMFAqrReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAqrReq(%+v)", *p)
}

type GetMFAqrResp struct {
	Base   *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	QrCode string          `thrift:"qr_code,2" frugal:"2,default,string" json:"qr_code"`
}

func NewGetMFAqrResp() *GetMFAqrResp {
	return &GetMFAqrResp{}
}

func (p *GetMFAqrResp) InitDefault() {
}

var GetMFAqrResp_Base_DEFAULT *model.BaseResp

func (p *GetMFAqrResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetMFAqrResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetMFAqrResp) GetQrCode() (v string) {
	return p.QrCode
}
func (p *GetMFAqrResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetMFAqrResp) SetQrCode(val string) {
	p.QrCode = val
}

func (p *GetMFAqrResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetMFAqrResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAqrResp(%+v)", *p)
}

type BindMFAReq struct {
	MfaCode string `thrift:"mfa_code,1" frugal:"1,default,string" json:"mfa_code"`
}

func NewBindMFAReq() *BindMFAReq {
	return &BindMFAReq{}
}

func (p *BindMFAReq) InitDefault() {
}

func (p *BindMFAReq) GetMfaCode() (v string) {
	return p.MfaCode
}
func (p *BindMFAReq) SetMfaCode(val string) {
	p.MfaCode = val
}

func (p *BindMFAReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMFAReq(%+v)", *p)
}

type BindMFAResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewBindMFAResp() *BindMFAResp {
	return &BindMFAResp{}
}

func (p *BindMFAResp) InitDefault() {
}

var BindMFAResp_Base_DEFAULT *model.BaseResp

func (p *BindMFAResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return BindMFAResp_Base_DEFAULT
	}
	return p.Base
}
func (p *BindMFAResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *BindMFAResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *BindMFAResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMFAResp(%+v)", *p)
}

type UnbindMFAReq struct {
	MfaCode string `thrift:"mfa_code,2" frugal:"2,default,string" json:"mfa_code"`
}

func NewUnbindMFAReq() *UnbindMFAReq {
	return &UnbindMFAReq{}
}

func (p *UnbindMFAReq) InitDefault() {
}

func (p *UnbindMFAReq) GetMfaCode() (v string) {
	return p.MfaCode
}
func (p *UnbindMFAReq) SetMfaCode(val string) {
	p.MfaCode = val
}

func (p *UnbindMFAReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindMFAReq(%+v)", *p)
}

type UnbindMFAResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewUnbindMFAResp() *UnbindMFAResp {
	return &UnbindMFAResp{}
}

func (p *UnbindMFAResp) InitDefault() {
}

var UnbindMFAResp_Base_DEFAULT *model.BaseResp

func (p *UnbindMFAResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UnbindMFAResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UnbindMFAResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UnbindMFAResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UnbindMFAResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindMFAResp(%+v)", *p)
}

type RefreshTokenReq struct {
	Authorization string `thrift:"authorization,1" frugal:"1,default,string" json:"authorization"`
}

func NewRefreshTokenReq() *RefreshTokenReq {
	return &RefreshTokenReq{}
}

func (p *RefreshTokenReq) InitDefault() {
}

func (p *RefreshTokenReq) GetAuthorization() (v string) {
	return p.Authorization
}
func (p *RefreshTokenReq) SetAuthorization(val string) {
	p.Authorization = val
}

func (p *RefreshTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenReq(%+v)", *p)
}

type RefreshTokenResp struct {
	Base          *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	Authorization string          `thrift:"authorization,2" frugal:"2,default,string" json:"authorization"`
}

func NewRefreshTokenResp() *RefreshTokenResp {
	return &RefreshTokenResp{}
}

func (p *RefreshTokenResp) InitDefault() {
}

var RefreshTokenResp_Base_DEFAULT *model.BaseResp

func (p *RefreshTokenResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RefreshTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RefreshTokenResp) GetAuthorization() (v string) {
	return p.Authorization
}
func (p *RefreshTokenResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *RefreshTokenResp) SetAuthorization(val string) {
	p.Authorization = val
}

func (p *RefreshTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenResp(%+v)", *p)
}

type AuthService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	GetMFAqr(ctx context.Context, req *GetMFAqrReq) (r *GetMFAqrResp, err error)

	BindMFA(ctx context.Context, req *BindMFAReq) (r *BindMFAResp, err error)

	UnbindMFA(ctx context.Context, req *UnbindMFAReq) (r *UnbindMFAResp, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenReq) (r *RefreshTokenResp, err error)
}
