// Code generated by Kitex v0.16.3. DO NOT EDIT.

package auth

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/Sna-ken/videoweb/kitex_gen/model"
)

var (
	_ = model.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type AuthServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewAuthServiceRegisterArgs() *AuthServiceRegisterArgs {
	return &AuthServiceRegisterArgs{}
}

func (p *AuthServiceRegisterArgs) InitDefault() {
}

var AuthServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *AuthServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return AuthServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *AuthServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRegisterArgs(%+v)", *p)
}

func (p *AuthServiceRegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewAuthServiceRegisterResult() *AuthServiceRegisterResult {
	return &AuthServiceRegisterResult{}
}

func (p *AuthServiceRegisterResult) InitDefault() {
}

var AuthServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *AuthServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return AuthServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *AuthServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRegisterResult(%+v)", *p)
}

func (p *AuthServiceRegisterResult) GetResult() interface{} {
	return p.Success
}

type AuthServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewAuthServiceLoginArgs() *AuthServiceLoginArgs {
	return &AuthServiceLoginArgs{}
}

func (p *AuthServiceLoginArgs) InitDefault() {
}

var AuthServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *AuthServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return AuthServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *AuthServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginArgs(%+v)", *p)
}

func (p *AuthServiceLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewAuthServiceLoginResult() *AuthServiceLoginResult {
	return &AuthServiceLoginResult{}
}

func (p *AuthServiceLoginResult) InitDefault() {
}

var AuthServiceLoginResult_Success_DEFAULT *LoginResp

func (p *AuthServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return AuthServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *AuthServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginResult(%+v)", *p)
}

func (p *AuthServiceLoginResult) GetResult() interface{} {
	return p.Success
}

type AuthServiceGetMFAqrArgs struct {
	Req *GetMFAqrReq `thrift:"req,1" frugal:"1,default,GetMFAqrReq" json:"req"`
}

func NewAuthServiceGetMFAqrArgs() *AuthServiceGetMFAqrArgs {
	return &AuthServiceGetMFAqrArgs{}
}

func (p *AuthServiceGetMFAqrArgs) InitDefault() {
}

var AuthServiceGetMFAqrArgs_Req_DEFAULT *GetMFAqrReq

func (p *AuthServiceGetMFAqrArgs) GetReq() (v *GetMFAqrReq) {
	if !p.IsSetReq() {
		return AuthServiceGetMFAqrArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceGetMFAqrArgs) SetReq(val *GetMFAqrReq) {
	p.Req = val
}

func (p *AuthServiceGetMFAqrArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceGetMFAqrArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceGetMFAqrArgs(%+v)", *p)
}

func (p *AuthServiceGetMFAqrArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceGetMFAqrResult struct {
	Success *GetMFAqrResp `thrift:"success,0,optional" frugal:"0,optional,GetMFAqrResp" json:"success,omitempty"`
}

func NewAuthServiceGetMFAqrResult() *AuthServiceGetMFAqrResult {
	return &AuthServiceGetMFAqrResult{}
}

func (p *AuthServiceGetMFAqrResult) InitDefault() {
}

var AuthServiceGetMFAqrResult_Success_DEFAULT *GetMFAqrResp

func (p *AuthServiceGetMFAqrResult) GetSuccess() (v *GetMFAqrResp) {
	if !p.IsSetSuccess() {
		return AuthServiceGetMFAqrResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceGetMFAqrResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMFAqrResp)
}

func (p *AuthServiceGetMFAqrResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceGetMFAqrResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceGetMFAqrResult(%+v)", *p)
}

func (p *AuthServiceGetMFAqrResult) GetResult() interface{} {
	return p.Success
}

type AuthServiceBindMFAArgs struct {
	Req *BindMFAReq `thrift:"req,1" frugal:"1,default,BindMFAReq" json:"req"`
}

func NewAuthServiceBindMFAArgs() *AuthServiceBindMFAArgs {
	return &AuthServiceBindMFAArgs{}
}

func (p *AuthServiceBindMFAArgs) InitDefault() {
}

var AuthServiceBindMFAArgs_Req_DEFAULT *BindMFAReq

func (p *AuthServiceBindMFAArgs) GetReq() (v *BindMFAReq) {
	if !p.IsSetReq() {
		return AuthServiceBindMFAArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceBindMFAArgs) SetReq(val *BindMFAReq) {
	p.Req = val
}

func (p *AuthServiceBindMFAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceBindMFAArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceBindMFAArgs(%+v)", *p)
}

func (p *AuthServiceBindMFAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceBindMFAResult struct {
	Success *BindMFAResp `thrift:"success,0,optional" frugal:"0,optional,BindMFAResp" json:"success,omitempty"`
}

func NewAuthServiceBindMFAResult() *AuthServiceBindMFAResult {
	return &AuthServiceBindMFAResult{}
}

func (p *AuthServiceBindMFAResult) InitDefault() {
}

var AuthServiceBindMFAResult_Success_DEFAULT *BindMFAResp

func (p *AuthServiceBindMFAResult) GetSuccess() (v *BindMFAResp) {
	if !p.IsSetSuccess() {
		return AuthServiceBindMFAResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceBindMFAResult) SetSuccess(x interface{}) {
	p.Success = x.(*BindMFAResp)
}

func (p *AuthServiceBindMFAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceBindMFAResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceBindMFAResult(%+v)", *p)
}

func (p *AuthServiceBindMFAResult) GetResult() interface{} {
	return p.Success
}

type AuthServiceUnbindMFAArgs struct {
	Req *UnbindMFAReq `thrift:"req,1" frugal:"1,default,UnbindMFAReq" json:"req"`
}

func NewAuthServiceUnbindMFAArgs() *AuthServiceUnbindMFAArgs {
	return &AuthServiceUnbindMFAArgs{}
}

func (p *AuthServiceUnbindMFAArgs) InitDefault() {
}

var AuthServiceUnbindMFAArgs_Req_DEFAULT *UnbindMFAReq

func (p *AuthServiceUnbindMFAArgs) GetReq() (v *UnbindMFAReq) {
	if !p.IsSetReq() {
		return AuthServiceUnbindMFAArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceUnbindMFAArgs) SetReq(val *UnbindMFAReq) {
	p.Req = val
}

func (p *AuthServiceUnbindMFAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceUnbindMFAArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceUnbindMFAArgs(%+v)", *p)
}

func (p *AuthServiceUnbindMFAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceUnbindMFAResult struct {
	Success *UnbindMFAResp `thrift:"success,0,optional" frugal:"0,optional,UnbindMFAResp" json:"success,omitempty"`
}

func NewAuthServiceUnbindMFAResult() *AuthServiceUnbindMFAResult {
	return &AuthServiceUnbindMFAResult{}
}

func (p *AuthServiceUnbindMFAResult) InitDefault() {
}

var AuthServiceUnbindMFAResult_Success_DEFAULT *UnbindMFAResp

func (p *AuthServiceUnbindMFAResult) GetSuccess() (v *UnbindMFAResp) {
	if !p.IsSetSuccess() {
		return AuthServiceUnbindMFAResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceUnbindMFAResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnbindMFAResp)
}

func (p *AuthServiceUnbindMFAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceUnbindMFAResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceUnbindMFAResult(%+v)", *p)
}

func (p *AuthServiceUnbindMFAResult) GetResult() interface{} {
	return p.Success
}

type AuthServiceRefreshTokenArgs struct {
	Req *RefreshTokenReq `thrift:"req,1" frugal:"1,default,RefreshTokenReq" json:"req"`
}

func NewAuthServiceRefreshTokenArgs() *AuthServiceRefreshTokenArgs {
	return &AuthServiceRefreshTokenArgs{}
}

func (p *AuthServiceRefreshTokenArgs) InitDefault() {
}

var AuthServiceRefreshTokenArgs_Req_DEFAULT *RefreshTokenReq

func (p *AuthServiceRefreshTokenArgs) GetReq() (v *RefreshTokenReq) {
	if !p.IsSetReq() {
		return AuthServiceRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceRefreshTokenArgs) SetReq(val *RefreshTokenReq) {
	p.Req = val
}

func (p *AuthServiceRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenArgs(%+v)", *p)
}

func (p *AuthServiceRefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AuthServiceRefreshTokenResult struct {
	Success *RefreshTokenResp `thrift:"success,0,optional" frugal:"0,optional,RefreshTokenResp" json:"success,omitempty"`
}

func NewAuthServiceRefreshTokenResult() *AuthServiceRefreshTokenResult {
	return &AuthServiceRefreshTokenResult{}
}

func (p *AuthServiceRefreshTokenResult) InitDefault() {
}

var AuthServiceRefreshTokenResult_Success_DEFAULT *RefreshTokenResp

func (p *AuthServiceRefreshTokenResult) GetSuccess() (v *RefreshTokenResp) {
	if !p.IsSetSuccess() {
		return AuthServiceRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshTokenResp)
}

func (p *AuthServiceRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenResult(%+v)", *p)
}

func (p *AuthServiceRefreshTokenResult) GetResult() interface{} {
	return p.Success
}
