// Code generated by hertz generator.

package video

import (
	"github.com/Sna-ken/videoweb/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuth(),
	}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}
