// Code generated by Kitex v0.16.3. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	auth "github.com/Sna-ken/videoweb/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newAuthServiceRegisterArgs,
		newAuthServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newAuthServiceLoginArgs,
		newAuthServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newAuthServiceLogoutArgs,
		newAuthServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMFAqr": kitex.NewMethodInfo(
		getMFAqrHandler,
		newAuthServiceGetMFAqrArgs,
		newAuthServiceGetMFAqrResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindMFA": kitex.NewMethodInfo(
		bindMFAHandler,
		newAuthServiceBindMFAArgs,
		newAuthServiceBindMFAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbindMFA": kitex.NewMethodInfo(
		unbindMFAHandler,
		newAuthServiceUnbindMFAArgs,
		newAuthServiceUnbindMFAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newAuthServiceRefreshTokenArgs,
		newAuthServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceRegisterArgs)
	realResult := result.(*auth.AuthServiceRegisterResult)
	success, err := handler.(auth.AuthService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceRegisterArgs() interface{} {
	return auth.NewAuthServiceRegisterArgs()
}

func newAuthServiceRegisterResult() interface{} {
	return auth.NewAuthServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceLoginArgs)
	realResult := result.(*auth.AuthServiceLoginResult)
	success, err := handler.(auth.AuthService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceLoginArgs() interface{} {
	return auth.NewAuthServiceLoginArgs()
}

func newAuthServiceLoginResult() interface{} {
	return auth.NewAuthServiceLoginResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceLogoutArgs)
	realResult := result.(*auth.AuthServiceLogoutResult)
	success, err := handler.(auth.AuthService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceLogoutArgs() interface{} {
	return auth.NewAuthServiceLogoutArgs()
}

func newAuthServiceLogoutResult() interface{} {
	return auth.NewAuthServiceLogoutResult()
}

func getMFAqrHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceGetMFAqrArgs)
	realResult := result.(*auth.AuthServiceGetMFAqrResult)
	success, err := handler.(auth.AuthService).GetMFAqr(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceGetMFAqrArgs() interface{} {
	return auth.NewAuthServiceGetMFAqrArgs()
}

func newAuthServiceGetMFAqrResult() interface{} {
	return auth.NewAuthServiceGetMFAqrResult()
}

func bindMFAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceBindMFAArgs)
	realResult := result.(*auth.AuthServiceBindMFAResult)
	success, err := handler.(auth.AuthService).BindMFA(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceBindMFAArgs() interface{} {
	return auth.NewAuthServiceBindMFAArgs()
}

func newAuthServiceBindMFAResult() interface{} {
	return auth.NewAuthServiceBindMFAResult()
}

func unbindMFAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceUnbindMFAArgs)
	realResult := result.(*auth.AuthServiceUnbindMFAResult)
	success, err := handler.(auth.AuthService).UnbindMFA(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceUnbindMFAArgs() interface{} {
	return auth.NewAuthServiceUnbindMFAArgs()
}

func newAuthServiceUnbindMFAResult() interface{} {
	return auth.NewAuthServiceUnbindMFAResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceRefreshTokenArgs)
	realResult := result.(*auth.AuthServiceRefreshTokenResult)
	success, err := handler.(auth.AuthService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceRefreshTokenArgs() interface{} {
	return auth.NewAuthServiceRefreshTokenArgs()
}

func newAuthServiceRefreshTokenResult() interface{} {
	return auth.NewAuthServiceRefreshTokenResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *auth.RegisterReq) (r *auth.RegisterResp, err error) {
	var _args auth.AuthServiceRegisterArgs
	_args.Req = req
	var _result auth.AuthServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *auth.LoginReq) (r *auth.LoginResp, err error) {
	var _args auth.AuthServiceLoginArgs
	_args.Req = req
	var _result auth.AuthServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *auth.LogoutReq) (r *auth.LogoutResp, err error) {
	var _args auth.AuthServiceLogoutArgs
	_args.Req = req
	var _result auth.AuthServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMFAqr(ctx context.Context, req *auth.GetMFAqrReq) (r *auth.GetMFAqrResp, err error) {
	var _args auth.AuthServiceGetMFAqrArgs
	_args.Req = req
	var _result auth.AuthServiceGetMFAqrResult
	if err = p.c.Call(ctx, "GetMFAqr", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindMFA(ctx context.Context, req *auth.BindMFAReq) (r *auth.BindMFAResp, err error) {
	var _args auth.AuthServiceBindMFAArgs
	_args.Req = req
	var _result auth.AuthServiceBindMFAResult
	if err = p.c.Call(ctx, "BindMFA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindMFA(ctx context.Context, req *auth.UnbindMFAReq) (r *auth.UnbindMFAResp, err error) {
	var _args auth.AuthServiceUnbindMFAArgs
	_args.Req = req
	var _result auth.AuthServiceUnbindMFAResult
	if err = p.c.Call(ctx, "UnbindMFA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *auth.RefreshTokenReq) (r *auth.RefreshTokenResp, err error) {
	var _args auth.AuthServiceRefreshTokenArgs
	_args.Req = req
	var _result auth.AuthServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
