// Code generated by hertz generator.

package main

import (
	"github.com/Sna-ken/videoweb/api/handler/client"
	"github.com/Sna-ken/videoweb/api/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	router.Register(h)
	h.Spin()
}

func initRPC() {
	if err := client.InitAuthServiceClient("127.0.0.1:20001"); err != nil {
		panic(err)
	}
}
