// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package model

import (
	"fmt"
)

type BaseResp struct {
	Code int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int64) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

type UserInfo struct {
	UserId        string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Username      string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Avatar        string `thrift:"avatar,3" frugal:"3,default,string" json:"avatar"`
	Signature     string `thrift:"signature,4" frugal:"4,default,string" json:"signature"`
	FollowCount   int32  `thrift:"follow_count,5" frugal:"5,default,i32" json:"follow_count"`
	FollowerCount int32  `thrift:"follower_count,6" frugal:"6,default,i32" json:"follower_count"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v string) {
	return p.UserId
}

func (p *UserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *UserInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserInfo) GetSignature() (v string) {
	return p.Signature
}

func (p *UserInfo) GetFollowCount() (v int32) {
	return p.FollowCount
}

func (p *UserInfo) GetFollowerCount() (v int32) {
	return p.FollowerCount
}
func (p *UserInfo) SetUserId(val string) {
	p.UserId = val
}
func (p *UserInfo) SetUsername(val string) {
	p.Username = val
}
func (p *UserInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *UserInfo) SetSignature(val string) {
	p.Signature = val
}
func (p *UserInfo) SetFollowCount(val int32) {
	p.FollowCount = val
}
func (p *UserInfo) SetFollowerCount(val int32) {
	p.FollowerCount = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}
