// Code generated by hertz generator.

package video

import (
	"context"
	"errors"

	video "github.com/Sna-ken/videoweb/biz/model/video"
	service "github.com/Sna-ken/videoweb/biz/service/video"
	"github.com/Sna-ken/videoweb/pkg/e"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Publish .
// @router /video/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishReq
	coverfile, err := c.FormFile("cover")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.PublishResp{
			Base: &video.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}
	videofile, err := c.FormFile("video")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.PublishResp{
			Base: &video.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	videoService := service.NewVideoService(ctx)
	userID := c.GetString("user_id")

	err = videoService.PublishService(&req, userID, coverfile, videofile)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &video.PublishResp{
				Base: &video.Base{Code: int32(e.Code), Msg: "Publish failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, &video.PublishResp{
		Base: &video.Base{Code: consts.StatusOK, Msg: "Video published successfully"},
	})
}

// List .
// @router /video/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.ListReq
	err = c.BindAndValidate(&req)
	resp := new(video.ListResp)

	videoService := service.NewVideoService(ctx)
	userID := c.GetString("user_id")

	err, resp = videoService.ListService(&req, userID)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &video.ListResp{
				Base: &video.Base{Code: int32(e.Code), Msg: "Failed to fetch video list:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// Popular .
// @router /video/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PopularReq
	err = c.BindAndValidate(&req)
	resp := new(video.PopularResp)
	videoService := service.NewVideoService(ctx)

	err, resp = videoService.PopularService(&req)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &video.PopularResp{
				Base: &video.Base{Code: int32(e.Code), Msg: "Failed to fetch popular videos:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// Search
// @router /video/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.SearchReq
	err = c.BindAndValidate(&req)
	resp := new(video.SearchResp)
	videoService := service.NewVideoService(ctx)

	err, resp = videoService.SearchService(&req)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &video.SearchResp{
				Base: &video.Base{Code: int32(e.Code), Msg: "Failed to search videos:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}
