// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/Sna-ken/videoweb/api/handler/client"
	api "github.com/Sna-ken/videoweb/api/model/api"
	"github.com/Sna-ken/videoweb/kitex_gen/auth"
	"github.com/Sna-ken/videoweb/pkg/base"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMFAqr .
// @router /api/v1/auth/mfa/qr [GET]
func GetMFAqr(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetMFAqrReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetMFAqrResp)

	c.JSON(consts.StatusOK, resp)
}

// BindMFA .
// @router /api/v1/auth/mfa/bind [POST]
func BindMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.BindMFAReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.BindMFAResp)

	c.JSON(consts.StatusOK, resp)
}

// UnbindMFA .
// @router /api/v1/auth/mfa/unbind [POST]
func UnbindMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UnbindMFAReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UnbindMFAResp)

	c.JSON(consts.StatusOK, resp)
}

// RefreshToken .
// @router /api/v1/auth/token/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RefreshTokenReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.RefreshTokenResp)

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /api/v1/auth/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrHTTPResp(c, err)
		return
	}

	RPCresp, err := client.AuthServiceClient.Register(ctx, &auth.RegisterReq{
		Username: req.Username,
		Password: req.Password,
	})

	if err != nil {
		base.ErrHTTPRespWithData(c, err, RPCresp)
		return
	}

	base.SuccessHTTPRespWithData(c, RPCresp)
}

// Login .
// @router /api/v1/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.LoginResp)

	c.JSON(consts.StatusOK, resp)
}
