// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/Sna-ken/videoweb/api/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserInfo .
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetUserInfoResp)

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /api/v1/user/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UploadAvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UploadAvatarResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateSignature .
// @router /api/v1/user/signature [PUT]
func UpdateSignature(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateSignatureReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateSignatureResp)

	c.JSON(consts.StatusOK, resp)
}
