mysql:
  username: root
  password: root
  host: localhost
  port: "3306"
  name: videodb

redis:
  host: redis
  port: "6379"
  password: ""
  db: 0

jwt:
  access_token_secret: your-access-token-secret-key
  refresh_token_secret: your-refresh-token-secret-key
  access_token_expiry: 180   # 3分钟
  refresh_token_expiry: 604800 # 7天