// Code generated by hertz generator.

package main

import (
	"github.com/Sna-ken/videoweb/biz/handler/user"
	"github.com/Sna-ken/videoweb/config"
	"github.com/Sna-ken/videoweb/internal/dao"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	config.InitMysql()
	config.InitRedis()

	if config.MYSQLDB == nil {
		panic("Mysql connection failed")
	}
	if config.REDISDB == nil {
		panic("Redis connection failed")
	}

	h := server.Default()
	config.MYSQLDB.AutoMigrate(&dao.User{})

	h.StaticFS("/static", &app.FS{Root: "./", GenerateIndexPages: true}) //root不要设置成./static T-T
	h.POST("/user/register", user.Register)
	h.Spin()
}
