// Code generated by hertz generator.

package main

import (
	"github.com/Sna-ken/videoweb/config"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	config.InitMysql()
	config.InitRedis()

	if config.MYSQLDB == nil {
		panic("Mysql connection failed")
	}
	if config.REDISDB == nil {
		panic("Redis connection failed")
	}

	h := server.Default()

	h.Spin()
}
