// Code generated by hertz generator. DO NOT EDIT.

package router

import "github.com/cloudwego/hertz/pkg/app/server"

// Register registers generated and customized routes.
func Register(r *server.Hertz) {
	GeneratedRegister(r)
	CustomizedRegister(r)
}
