// Code generated by hertz generator.

package router

import "github.com/cloudwego/hertz/pkg/app/server"

// CustomizedRegister registers routes that are not defined in IDL.
func CustomizedRegister(r *server.Hertz) {
	// Register custom routes here.
}
