// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interact "github.com/Sna-ken/videoweb/biz/router/interact"
	social "github.com/Sna-ken/videoweb/biz/router/social"
	user "github.com/Sna-ken/videoweb/biz/router/user"
	video "github.com/Sna-ken/videoweb/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social.Register(r)

	interact.Register(r)

	video.Register(r)

	user.Register(r)
}
