// Code generated by hertz generator.

package main

import (
	"context"

	"github.com/Sna-ken/videoweb/ai/agent"
	"github.com/Sna-ken/videoweb/biz/router"
	"github.com/Sna-ken/videoweb/internal/model"
	"github.com/Sna-ken/videoweb/ws"

	"github.com/Sna-ken/videoweb/biz/router/chat"
	"github.com/Sna-ken/videoweb/biz/router/static"
	"github.com/Sna-ken/videoweb/config"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	config.Init()
	config.InitMysql()
	config.InitRedis()
	config.InitAIConfig()

	if config.MYSQLDB == nil {
		panic("Mysql connection failed")
	}
	if config.REDISDB == nil {
		panic("Redis connection failed")

	}

	config.InitTable()

	h := server.New(
		server.WithMaxRequestBodySize(500 * 1024 * 1024), // 500MB
	)

	router.GeneratedRegister(h)
	static.GeneratedRegisterStaticFS(h)
	chat.GeneratedRegister(h)

	ctx := context.Background()

	agent.InitAgent(ctx)

	ws.ManagerInstance.OnNewMessage = func(msg *model.Message) {
		agent.OneNewMessage(context.Background(), msg,
			agent.MentionTrigger, agent.EmotionTrigger, agent.SilenceTrigger, agent.DecisionChain, agent.GenerationChain)
	}

	h.Spin()
}
