// Code generated by hertz generator.

package user

import (
	"context"
	"errors"

	user "github.com/Sna-ken/videoweb/biz/model/user"
	service "github.com/Sna-ken/videoweb/biz/service/user"
	"github.com/Sna-ken/videoweb/pkg/e"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.RegisterResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)

	if err := userService.RegisterService(&req); err != nil {
		switch {
		case errors.Is(err, e.ErrHasedPassword):
			c.JSON(consts.StatusInternalServerError, &user.RegisterResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "Register failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrUserHasExisted):
			c.JSON(consts.StatusConflict, &user.RegisterResp{
				Base: &user.Base{Code: consts.StatusConflict, Msg: "Register failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &user.RegisterResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "Register failed:" + err.Error()},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, &user.RegisterResp{
		Base: &user.Base{Code: consts.StatusOK, Msg: "User register successfully"},
	})
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.LoginResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)

	err, resp := userService.LoginService(&req)

	if err != nil {
		switch {
		case errors.Is(err, e.ErrUserNotFound):
			c.JSON(consts.StatusUnauthorized, &user.LoginResp{
				Base: &user.Base{Code: consts.StatusUnauthorized, Msg: "Login failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrWrongPassword):
			c.JSON(consts.StatusUnauthorized, &user.LoginResp{
				Base: &user.Base{Code: consts.StatusUnauthorized, Msg: "Login failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrGenerateToken):
			c.JSON(consts.StatusInternalServerError, &user.LoginResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "Login failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &user.LoginResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "Login failed:" + err.Error()},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// UserInfo .
// @router /user/info [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.UserInfoResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err, resp := userService.UserInfoService(&req, userID)

	if err != nil {
		switch {
		case errors.Is(err, e.ErrUserIDNotFound):
			c.JSON(consts.StatusUnauthorized, &user.UserInfoResp{
				Base: &user.Base{Code: consts.StatusUnauthorized, Msg: "fetch user info failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrUserNotFound):
			c.JSON(consts.StatusUnauthorized, &user.UserInfoResp{
				Base: &user.Base{Code: consts.StatusUnauthorized, Msg: "fetch user info failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &user.UserInfoResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "fetch user info failed:" + err.Error()},
			})
			return

		}
	}

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /user/avatar [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UploadAvatarReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.UploadAvatarResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err = userService.UploadAvatarService(&req, userID)

	if err != nil {
		switch {
		case errors.Is(err, e.ErrUserIDNotFound):
			c.JSON(consts.StatusUnauthorized, &user.UploadAvatarResp{
				Base: &user.Base{Code: consts.StatusUnauthorized, Msg: "upload avatar failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrFileRequired):
			c.JSON(consts.StatusBadRequest, &user.UploadAvatarResp{
				Base: &user.Base{Code: consts.StatusBadRequest, Msg: "upload avatar failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrFileSaveFailed):
			c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "upload avatar failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrFileDeleteFailed):
			c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "upload avatar failed:" + err.Error()},
			})
			return

		case errors.Is(err, e.ErrDB):
			c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResp{
				Base: &user.Base{Code: consts.StatusInternalServerError, Msg: "upload avatar failed:" + err.Error()},
			})
			return

		}
	}

	c.JSON(consts.StatusOK, &user.UploadAvatarResp{
		Base: &user.Base{Code: consts.StatusOK, Msg: "avatar upload successfully"},
	})
}
