// Code generated by hertz generator.

package user

import (
	"context"
	"errors"

	user "github.com/Sna-ken/videoweb/biz/model/user"
	service "github.com/Sna-ken/videoweb/biz/service/user"
	"github.com/Sna-ken/videoweb/pkg/e"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.RegisterResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)

	if err := userService.RegisterService(&req); err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.RegisterResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "User register failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, &user.RegisterResp{
		Base: &user.Base{Code: consts.StatusOK, Msg: "User register successfully"},
	})
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.LoginResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)

	err, resp := userService.LoginService(&req)

	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.LoginResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "User login failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// UserInfo .
// @router /user/info [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.UserInfoResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err, resp := userService.UserInfoService(&req, userID)

	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.UserInfoResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "Fetch user info failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /user/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UploadAvatarReq
	file, err := c.FormFile("avatar")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.UploadAvatarResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err = userService.UploadAvatarService(&req, userID, file)

	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.UploadAvatarResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "Avatar upload failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, &user.UploadAvatarResp{
		Base: &user.Base{Code: consts.StatusOK, Msg: "avatar upload successfully"},
	})
}

// GetMFAqr .
// @router /user/mfa/qrcode [GET]
func GetMFAqr(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetMFAqrReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.GetMFAqrResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err, resp := userService.GetMFAqrService(&req, userID)

	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.GetMFAqrResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "Get MFA QR code failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// BindMFA .
// @router /user/mfa/bind [POST]
func BindMFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.BindMFAReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.BindMFAResp{
			Base: &user.Base{Code: consts.StatusBadRequest, Msg: "Invalid input:" + err.Error()},
		})
		return
	}

	userService := service.NewUserService(ctx)
	userID := c.GetString("user_id")
	err = userService.BindMFAService(&req, userID)

	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &user.BindMFAResp{
				Base: &user.Base{Code: int32(e.Code), Msg: "Bind MFA failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, user.BindMFAResp{
		Base: &user.Base{Code: consts.StatusOK, Msg: "bind MFA successfully"},
	})
}
