CREATE TABLE users(
    id VARCHAR(64) NOT NULL COMMENT 'ID',
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    nickname VARCHAR(64) NOT NULL COMMENT '用户名',
    avatar VARCHAR(256) NOT NULL DEFAULT '' COMMENT '头像',
    signature VARCHAR(256) NOT NULL DEFAULT '' COMMENT '个性签名',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_id (user_id),
    UNIQUE KEY uk_nickname (nickname)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE auth_accounts (
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    username VARCHAR(64) NOT NULL COMMENT '用户名',
    password VARCHAR(128) NOT NULL COMMENT '密码哈希',
    mfa_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用MFA(0:未启用,1:已启用)',
    mfa_secret VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'MFA密钥',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (user_id),
    UNIQUE KEY uk_username (username)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
