// Code generated by hertz generator.

package interact

import (
	"github.com/Sna-ken/videoweb/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JWTAuth(),
	}

}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentpublishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
