// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package model

import (
	"fmt"
)

type BaseResp struct {
	Code int64  `thrift:"code,1" form:"code" json:"code" query:"code"`
	Msg  string `thrift:"msg,2" form:"msg" json:"msg" query:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

type UserInfo struct {
	UserID        string `thrift:"user_id,1" form:"user_id" json:"user_id" query:"user_id"`
	Username      string `thrift:"username,2" form:"username" json:"username" query:"username"`
	Avatar        string `thrift:"avatar,3" form:"avatar" json:"avatar" query:"avatar"`
	Signature     string `thrift:"signature,4" form:"signature" json:"signature" query:"signature"`
	FollowCount   int32  `thrift:"follow_count,5" form:"follow_count" json:"follow_count" query:"follow_count"`
	FollowerCount int32  `thrift:"follower_count,6" form:"follower_count" json:"follower_count" query:"follower_count"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserID() (v string) {
	return p.UserID
}

func (p *UserInfo) GetUsername() (v string) {
	return p.Username
}

func (p *UserInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserInfo) GetSignature() (v string) {
	return p.Signature
}

func (p *UserInfo) GetFollowCount() (v int32) {
	return p.FollowCount
}

func (p *UserInfo) GetFollowerCount() (v int32) {
	return p.FollowerCount
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}
