// Code generated by hertz generator.

package interact

import (
	"context"
	"errors"

	interact "github.com/Sna-ken/videoweb/biz/model/interact"
	service "github.com/Sna-ken/videoweb/biz/service/interact"
	"github.com/Sna-ken/videoweb/pkg/e"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LikeAction .
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.LikeActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	interactService := service.NewInteractService(ctx)
	userID := c.GetString("user_id")

	err = interactService.LikeActionService(&req, userID)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &interact.LikeActionResp{
				Base: &interact.Base{Code: int32(e.Code), Msg: "Like action failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, interact.LikeActionResp{
		Base: &interact.Base{Code: consts.StatusOK, Msg: "Like action successfully"},
	})
}

// LikeList .
// @router /like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.LikeListReq
	resp := new(interact.LikeListResp)

	interactService := service.NewInteractService(ctx)

	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	err, resp = interactService.LikeListService(&req)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &interact.LikeListResp{
				Base: &interact.Base{Code: int32(e.Code), Msg: "Failed to fetch liked videos:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// CommentPublish .
// @router /comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.CommentPublishReq
	err = c.BindAndValidate(&req)

	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	interactService := service.NewInteractService(ctx)
	userID := c.GetString("user_id")

	err = interactService.CommentPublishService(&req, userID)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &interact.CommentPublishResp{
				Base: &interact.Base{Code: int32(e.Code), Msg: "Comment publish failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, interact.CommentPublishResp{
		Base: &interact.Base{Code: consts.StatusOK, Msg: "Comment publish successfully"},
	})
}

// CommentList .
// @router /comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.CommentListReq
	resp := new(interact.CommentListResp)

	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}
	interactService := service.NewInteractService(ctx)
	err, resp = interactService.CommentListService(&req)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &interact.CommentListResp{
				Base: &interact.Base{Code: int32(e.Code), Msg: "Comment list fetch failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// CommentDelete .
// @router /comment/delete [DELETE]
func CommentDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interact.CommentDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}
	interactService := service.NewInteractService(ctx)
	userID := c.GetString("user_id")

	err = interactService.CommentDeleteService(&req, userID)
	if err != nil {
		var e *e.Error
		if errors.As(err, &e) {
			c.JSON(e.Code, &interact.CommentDeleteResp{
				Base: &interact.Base{Code: int32(e.Code), Msg: "Comment delete failed:" + e.Msg},
			})
			return
		}
	}

	c.JSON(consts.StatusOK, interact.CommentDeleteResp{
		Base: &interact.Base{Code: consts.StatusOK, Msg: "Delete comment successfully"},
	})
}
