// Code generated by hertz generator.

package api

import (
	"github.com/Sna-ken/videoweb/api/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindmfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Authorization(),
	}
}

func _getmfaqrMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Authorization(),
	}
}

func _unbindmfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Authorization(),
	}
}

func _tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.RefreshAuthorization(),
	}
}

func _userMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Authorization(),
	}
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Authorization(),
	}
}

func _userifoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesignatureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}
