// Code generated by Kitex v0.16.3. DO NOT EDIT.

package user

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/Sna-ken/videoweb/kitex_gen/model"
)

var (
	_ = model.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

func (p *UserServiceGetUserInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

func (p *UserServiceGetUserInfoResult) GetResult() interface{} {
	return p.Success
}

type UserServiceUploadAvatarArgs struct {
	Req *UploadAvatarReq `thrift:"req,1" frugal:"1,default,UploadAvatarReq" json:"req"`
}

func NewUserServiceUploadAvatarArgs() *UserServiceUploadAvatarArgs {
	return &UserServiceUploadAvatarArgs{}
}

func (p *UserServiceUploadAvatarArgs) InitDefault() {
}

var UserServiceUploadAvatarArgs_Req_DEFAULT *UploadAvatarReq

func (p *UserServiceUploadAvatarArgs) GetReq() (v *UploadAvatarReq) {
	if !p.IsSetReq() {
		return UserServiceUploadAvatarArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUploadAvatarArgs) SetReq(val *UploadAvatarReq) {
	p.Req = val
}

func (p *UserServiceUploadAvatarArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUploadAvatarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadAvatarArgs(%+v)", *p)
}

func (p *UserServiceUploadAvatarArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserServiceUploadAvatarResult struct {
	Success *UploadAvatarResp `thrift:"success,0,optional" frugal:"0,optional,UploadAvatarResp" json:"success,omitempty"`
}

func NewUserServiceUploadAvatarResult() *UserServiceUploadAvatarResult {
	return &UserServiceUploadAvatarResult{}
}

func (p *UserServiceUploadAvatarResult) InitDefault() {
}

var UserServiceUploadAvatarResult_Success_DEFAULT *UploadAvatarResp

func (p *UserServiceUploadAvatarResult) GetSuccess() (v *UploadAvatarResp) {
	if !p.IsSetSuccess() {
		return UserServiceUploadAvatarResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUploadAvatarResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadAvatarResp)
}

func (p *UserServiceUploadAvatarResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUploadAvatarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadAvatarResult(%+v)", *p)
}

func (p *UserServiceUploadAvatarResult) GetResult() interface{} {
	return p.Success
}

type UserServiceUpdateSignatureArgs struct {
	Req *UpdateSignatureReq `thrift:"req,1" frugal:"1,default,UpdateSignatureReq" json:"req"`
}

func NewUserServiceUpdateSignatureArgs() *UserServiceUpdateSignatureArgs {
	return &UserServiceUpdateSignatureArgs{}
}

func (p *UserServiceUpdateSignatureArgs) InitDefault() {
}

var UserServiceUpdateSignatureArgs_Req_DEFAULT *UpdateSignatureReq

func (p *UserServiceUpdateSignatureArgs) GetReq() (v *UpdateSignatureReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateSignatureArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateSignatureArgs) SetReq(val *UpdateSignatureReq) {
	p.Req = val
}

func (p *UserServiceUpdateSignatureArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateSignatureArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateSignatureArgs(%+v)", *p)
}

func (p *UserServiceUpdateSignatureArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserServiceUpdateSignatureResult struct {
	Success *UpdateSignatureResp `thrift:"success,0,optional" frugal:"0,optional,UpdateSignatureResp" json:"success,omitempty"`
}

func NewUserServiceUpdateSignatureResult() *UserServiceUpdateSignatureResult {
	return &UserServiceUpdateSignatureResult{}
}

func (p *UserServiceUpdateSignatureResult) InitDefault() {
}

var UserServiceUpdateSignatureResult_Success_DEFAULT *UpdateSignatureResp

func (p *UserServiceUpdateSignatureResult) GetSuccess() (v *UpdateSignatureResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateSignatureResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateSignatureResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateSignatureResp)
}

func (p *UserServiceUpdateSignatureResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateSignatureResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateSignatureResult(%+v)", *p)
}

func (p *UserServiceUpdateSignatureResult) GetResult() interface{} {
	return p.Success
}

type UserServiceCreateUserArgs struct {
	Req *CreateUserReq `thrift:"req,1" frugal:"1,default,CreateUserReq" json:"req"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Req_DEFAULT *CreateUserReq

func (p *UserServiceCreateUserArgs) GetReq() (v *CreateUserReq) {
	if !p.IsSetReq() {
		return UserServiceCreateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateUserArgs) SetReq(val *CreateUserReq) {
	p.Req = val
}

func (p *UserServiceCreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

func (p *UserServiceCreateUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResp `thrift:"success,0,optional" frugal:"0,optional,CreateUserResp" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResp

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResp)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

func (p *UserServiceCreateUserResult) GetResult() interface{} {
	return p.Success
}
