// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"github.com/Sna-ken/videoweb/kitex_gen/model"
)

type GetUserInfoReq struct {
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

type GetUserInfoResp struct {
	Base     *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
	UserInfo *model.UserInfo `thrift:"user_info,2" frugal:"2,default,model.UserInfo" json:"user_info"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_Base_DEFAULT *model.BaseResp

func (p *GetUserInfoResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetUserInfoResp_Base_DEFAULT
	}
	return p.Base
}

var GetUserInfoResp_UserInfo_DEFAULT *model.UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *model.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetUserInfoResp) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetUserInfoResp) SetUserInfo(val *model.UserInfo) {
	p.UserInfo = val
}

func (p *GetUserInfoResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

type UploadAvatarReq struct {
	Avatar string `thrift:"avatar,1" frugal:"1,default,string" json:"avatar"`
}

func NewUploadAvatarReq() *UploadAvatarReq {
	return &UploadAvatarReq{}
}

func (p *UploadAvatarReq) InitDefault() {
}

func (p *UploadAvatarReq) GetAvatar() (v string) {
	return p.Avatar
}
func (p *UploadAvatarReq) SetAvatar(val string) {
	p.Avatar = val
}

func (p *UploadAvatarReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarReq(%+v)", *p)
}

type UploadAvatarResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewUploadAvatarResp() *UploadAvatarResp {
	return &UploadAvatarResp{}
}

func (p *UploadAvatarResp) InitDefault() {
}

var UploadAvatarResp_Base_DEFAULT *model.BaseResp

func (p *UploadAvatarResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UploadAvatarResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UploadAvatarResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UploadAvatarResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UploadAvatarResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarResp(%+v)", *p)
}

type UpdateSignatureReq struct {
	Signature string `thrift:"signature,1" frugal:"1,default,string" json:"signature"`
}

func NewUpdateSignatureReq() *UpdateSignatureReq {
	return &UpdateSignatureReq{}
}

func (p *UpdateSignatureReq) InitDefault() {
}

func (p *UpdateSignatureReq) GetSignature() (v string) {
	return p.Signature
}
func (p *UpdateSignatureReq) SetSignature(val string) {
	p.Signature = val
}

func (p *UpdateSignatureReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateSignatureReq(%+v)", *p)
}

type UpdateSignatureResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewUpdateSignatureResp() *UpdateSignatureResp {
	return &UpdateSignatureResp{}
}

func (p *UpdateSignatureResp) InitDefault() {
}

var UpdateSignatureResp_Base_DEFAULT *model.BaseResp

func (p *UpdateSignatureResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UpdateSignatureResp_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateSignatureResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *UpdateSignatureResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateSignatureResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateSignatureResp(%+v)", *p)
}

type CreateUserReq struct {
	UserId   string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Username string `thrift:"username,2" frugal:"2,default,string" json:"username"`
}

func NewCreateUserReq() *CreateUserReq {
	return &CreateUserReq{}
}

func (p *CreateUserReq) InitDefault() {
}

func (p *CreateUserReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CreateUserReq) GetUsername() (v string) {
	return p.Username
}
func (p *CreateUserReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CreateUserReq) SetUsername(val string) {
	p.Username = val
}

func (p *CreateUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserReq(%+v)", *p)
}

type CreateUserResp struct {
	Base *model.BaseResp `thrift:"base,1" frugal:"1,default,model.BaseResp" json:"base"`
}

func NewCreateUserResp() *CreateUserResp {
	return &CreateUserResp{}
}

func (p *CreateUserResp) InitDefault() {
}

var CreateUserResp_Base_DEFAULT *model.BaseResp

func (p *CreateUserResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CreateUserResp_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateUserResp) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *CreateUserResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResp(%+v)", *p)
}

type UserService interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	UploadAvatar(ctx context.Context, req *UploadAvatarReq) (r *UploadAvatarResp, err error)

	UpdateSignature(ctx context.Context, req *UpdateSignatureReq) (r *UpdateSignatureResp, err error)

	CreateUser(ctx context.Context, req *CreateUserReq) (r *CreateUserResp, err error)
}
