// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"github.com/Sna-ken/videoweb/api/model/model"
)

// auth部分
type RegisterReq struct {
	Username string `thrift:"username,1" form:"username" json:"username" query:"username"`
	Password string `thrift:"password,2" form:"password" json:"password" query:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

type RegisterResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_Base_DEFAULT *model.BaseResp

func (p *RegisterResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RegisterResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RegisterResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

type LoginReq struct {
	Username string `thrift:"username,1" form:"username" json:"username" query:"username"`
	Password string `thrift:"password,2" form:"password" json:"password" query:"password"`
	MfaCode  string `thrift:"mfa_code,3" form:"mfa_code" json:"mfa_code" query:"mfa_code"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}

func (p *LoginReq) GetMfaCode() (v string) {
	return p.MfaCode
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

type LoginResp struct {
	Base         *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
	AccessToken  string          `thrift:"access_token,2" form:"access_token" json:"access_token" query:"access_token"`
	RefreshToken string          `thrift:"refresh_token,3" form:"refresh_token" json:"refresh_token" query:"refresh_token"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_Base_DEFAULT *model.BaseResp

func (p *LoginResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LoginResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LoginResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LoginResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LoginResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

type LogoutReq struct {
	RefreshToken string `thrift:"refresh_token,1" form:"refresh_token" json:"refresh_token" query:"refresh_token"`
}

func NewLogoutReq() *LogoutReq {
	return &LogoutReq{}
}

func (p *LogoutReq) InitDefault() {
}

func (p *LogoutReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LogoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutReq(%+v)", *p)
}

type LogoutResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewLogoutResp() *LogoutResp {
	return &LogoutResp{}
}

func (p *LogoutResp) InitDefault() {
}

var LogoutResp_Base_DEFAULT *model.BaseResp

func (p *LogoutResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return LogoutResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LogoutResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LogoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResp(%+v)", *p)
}

type GetMFAqrReq struct {
}

func NewGetMFAqrReq() *GetMFAqrReq {
	return &GetMFAqrReq{}
}

func (p *GetMFAqrReq) InitDefault() {
}

func (p *GetMFAqrReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAqrReq(%+v)", *p)
}

type GetMFAqrResp struct {
	Base   *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
	QrCode string          `thrift:"qr_code,2" form:"qr_code" json:"qr_code" query:"qr_code"`
}

func NewGetMFAqrResp() *GetMFAqrResp {
	return &GetMFAqrResp{}
}

func (p *GetMFAqrResp) InitDefault() {
}

var GetMFAqrResp_Base_DEFAULT *model.BaseResp

func (p *GetMFAqrResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetMFAqrResp_Base_DEFAULT
	}
	return p.Base
}

func (p *GetMFAqrResp) GetQrCode() (v string) {
	return p.QrCode
}

func (p *GetMFAqrResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetMFAqrResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMFAqrResp(%+v)", *p)
}

type BindMFAReq struct {
	MfaCode string `thrift:"mfa_code,1" form:"mfa_code" json:"mfa_code" query:"mfa_code"`
}

func NewBindMFAReq() *BindMFAReq {
	return &BindMFAReq{}
}

func (p *BindMFAReq) InitDefault() {
}

func (p *BindMFAReq) GetMfaCode() (v string) {
	return p.MfaCode
}

func (p *BindMFAReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMFAReq(%+v)", *p)
}

type BindMFAResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewBindMFAResp() *BindMFAResp {
	return &BindMFAResp{}
}

func (p *BindMFAResp) InitDefault() {
}

var BindMFAResp_Base_DEFAULT *model.BaseResp

func (p *BindMFAResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return BindMFAResp_Base_DEFAULT
	}
	return p.Base
}

func (p *BindMFAResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *BindMFAResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMFAResp(%+v)", *p)
}

type UnbindMFAReq struct {
	MfaCode string `thrift:"mfa_code,1" form:"mfa_code" json:"mfa_code" query:"mfa_code"`
}

func NewUnbindMFAReq() *UnbindMFAReq {
	return &UnbindMFAReq{}
}

func (p *UnbindMFAReq) InitDefault() {
}

func (p *UnbindMFAReq) GetMfaCode() (v string) {
	return p.MfaCode
}

func (p *UnbindMFAReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindMFAReq(%+v)", *p)
}

type UnbindMFAResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewUnbindMFAResp() *UnbindMFAResp {
	return &UnbindMFAResp{}
}

func (p *UnbindMFAResp) InitDefault() {
}

var UnbindMFAResp_Base_DEFAULT *model.BaseResp

func (p *UnbindMFAResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UnbindMFAResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UnbindMFAResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UnbindMFAResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindMFAResp(%+v)", *p)
}

type RefreshTokenReq struct {
	RefreshToken string `thrift:"refresh_token,1" form:"refresh_token" json:"refresh_token" query:"refresh_token"`
}

func NewRefreshTokenReq() *RefreshTokenReq {
	return &RefreshTokenReq{}
}

func (p *RefreshTokenReq) InitDefault() {
}

func (p *RefreshTokenReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenReq(%+v)", *p)
}

type RefreshTokenResp struct {
	Base        *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
	AccessToken string          `thrift:"access_token,2" form:"access_token" json:"access_token" query:"access_token"`
}

func NewRefreshTokenResp() *RefreshTokenResp {
	return &RefreshTokenResp{}
}

func (p *RefreshTokenResp) InitDefault() {
}

var RefreshTokenResp_Base_DEFAULT *model.BaseResp

func (p *RefreshTokenResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return RefreshTokenResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RefreshTokenResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *RefreshTokenResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshTokenResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenResp(%+v)", *p)
}

// user部分
type GetUserInfoReq struct {
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

type GetUserInfoResp struct {
	Base     *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
	UserInfo *model.UserInfo `thrift:"user_info,2" form:"user_info" json:"user_info" query:"user_info"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_Base_DEFAULT *model.BaseResp

func (p *GetUserInfoResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetUserInfoResp_Base_DEFAULT
	}
	return p.Base
}

var GetUserInfoResp_UserInfo_DEFAULT *model.UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *model.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}

func (p *GetUserInfoResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

type UploadAvatarReq struct {
	Avatar string `thrift:"avatar,1" form:"avatar" json:"avatar" query:"avatar"`
}

func NewUploadAvatarReq() *UploadAvatarReq {
	return &UploadAvatarReq{}
}

func (p *UploadAvatarReq) InitDefault() {
}

func (p *UploadAvatarReq) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UploadAvatarReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarReq(%+v)", *p)
}

type UploadAvatarResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewUploadAvatarResp() *UploadAvatarResp {
	return &UploadAvatarResp{}
}

func (p *UploadAvatarResp) InitDefault() {
}

var UploadAvatarResp_Base_DEFAULT *model.BaseResp

func (p *UploadAvatarResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UploadAvatarResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UploadAvatarResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UploadAvatarResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarResp(%+v)", *p)
}

type UpdateSignatureReq struct {
	Signature string `thrift:"signature,1" form:"signature" json:"signature" query:"signature"`
}

func NewUpdateSignatureReq() *UpdateSignatureReq {
	return &UpdateSignatureReq{}
}

func (p *UpdateSignatureReq) InitDefault() {
}

func (p *UpdateSignatureReq) GetSignature() (v string) {
	return p.Signature
}

func (p *UpdateSignatureReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateSignatureReq(%+v)", *p)
}

type UpdateSignatureResp struct {
	Base *model.BaseResp `thrift:"base,1" form:"base" json:"base" query:"base"`
}

func NewUpdateSignatureResp() *UpdateSignatureResp {
	return &UpdateSignatureResp{}
}

func (p *UpdateSignatureResp) InitDefault() {
}

var UpdateSignatureResp_Base_DEFAULT *model.BaseResp

func (p *UpdateSignatureResp) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return UpdateSignatureResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UpdateSignatureResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateSignatureResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateSignatureResp(%+v)", *p)
}

type AuthService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	Logout(ctx context.Context, req *LogoutReq) (r *LogoutResp, err error)

	GetMFAqr(ctx context.Context, req *GetMFAqrReq) (r *GetMFAqrResp, err error)

	BindMFA(ctx context.Context, req *BindMFAReq) (r *BindMFAResp, err error)

	UnbindMFA(ctx context.Context, req *UnbindMFAReq) (r *UnbindMFAResp, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenReq) (r *RefreshTokenResp, err error)
}

type UserService interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	UploadAvatar(ctx context.Context, req *UploadAvatarReq) (r *UploadAvatarResp, err error)

	UpdateSignature(ctx context.Context, req *UpdateSignatureReq) (r *UpdateSignatureResp, err error)
}
